== Übungsaufgabe 1 zu Modul 1b (Auffrischung Javascript)

Diese Aufgabe dient der Übung grundlegender Javascript-Anweisungen.

=== Platzhalter

Nachfolgend sind die spezifischen Parameter, die in der grundlegenden Einführung zu den Übungen erwähnt sind.

|===
|Platzhalter |Wert

|`<initial-github>`
|https://github.com/baitando/dhbw-distributed/tree/main/01b-auffrischung-js/uebung-1/initial

|`<initial-download>`
|https://baitando.github.io/down-git/#/home?url=https://github.com/baitando/dhbw-distributed/tree/main/01b-auffrischung-js/uebung-1/initial

|`<initial-ide`
|https://stackblitz.com/fork/github/baitando/dhbw-distributed/tree/main/01b-auffrischung-js/uebung-1/initial?file=index.html&terminal=stackblitz&title=%C3%9Cbungsaufgabe%201%20%7C%20Modul%201b%20%28Auffrischung%20Javascript%29
|===

=== Aufgabenbeschreibung

1.	Bearbeiten Sie die TODO-Kommentare im Code in der Reihenfolge ihrer Nummerierung.
Nutzen Sie hierzu auch die Hilfsmittel aus der Entwicklerwerkzeuge Ihres Browsers.
Überprüfen Sie insbesondere die Ausgaben auf der Entwicklerkonsole und führen Sie Ihre Anwendung mithilfe des Debuggers Schritt für Schritt aus.
2.	Rekapitulieren Sie die Inhalte der bisher besprochenen Folien zum Thema Javascript und testen Sie einige der Anweisungen und Programmierkonstrukte.

=== Lösungsbeispiel

Eine beispielhafte Lösung finden Sie auf GitHub unter https://github.com/baitando/dhbw-distributed/tree/main/01b-auffrischung-js/uebung-1/result.

Sie können dieses Lösungsbeispiel durch Öffnen der URL https://stackblitz.com/github/baitando/dhbw-distributed/tree/main/01b-auffrischung-js/uebung-1/result?file=index.html&terminal=stackblitz&title=L%C3%B6sungsbeispiel%20%C3%9Cbungsaufgabe%201%20%7C%20Modul%201b%20%28Auffrischung%20Javascript%29 im Browser direkt in der Online-Entwicklungsumgebung betrachten.

