== Übungsaufgabe 2 zu Modul 2b (Javascript im Backend)

In dieser Übungsaufgabe wird ein Teil der Backend-API der aus der vorhergehenden Lehrveranstaltung bekannten Web-Anwendung mittels Javascript und den Bordmitteln von Node.js realisiert.

=== Platzhalter

Nachfolgend sind die spezifischen Parameter, die in der grundlegenden Einführung zu den Übungen erwähnt sind.

|===
|Platzhalter |Wert

|`<initial-github>`
|https://github.com/baitando/dhbw-distributed/tree/main/02b-backend-js/uebung-2/initial

|`<initial-download>`
|https://baitando.github.io/down-git/#/home?url=https://github.com/baitando/dhbw-distributed/tree/main/02b-backend-js/uebung-2/initial

|`<initial-ide>`
|https://stackblitz.com/fork/github/baitando/dhbw-distributed/tree/main/02b-backend-js/uebung-2/initial?file=src/server.js&initialpath=/swagger-ui&title=%C3%9Cbungsaufgabe%202%20%7C%20Modul%202d%20%28Javascript%20im%20Backend%29
|===

=== Aufgabenbeschreibung

1.	Bearbeiten Sie die TODO-Kommentare im Code in der Reihenfolge ihrer Nummerierung.
2.  Setzen Sie nun die restlichen Bestandteile der bereitgestellten Spezifikation um.

=== Lösungsbeispiel

Eine beispielhafte Lösung finden Sie auf GitHub unter https://github.com/baitando/dhbw-distributed/tree/main/02b-backend-js/uebung-1/result.

Sie können dieses Lösungsbeispiel durch Öffnen der URL https://stackblitz.com/github/baitando/dhbw-distributed/tree/main/02b-backend-js/uebung-2/result?file=src/server.js&initialpath=/swagger-ui&title=L%C3%B6sungsbeispiel%20%C3%9Cbungsaufgabe%202%20%7C%20Modul%202d%20%28Javascript%20im%20Backend%29 im Browser direkt in der Online-Entwicklungsumgebung betrachten.
