name: Build Documents
on:
  push:
    branches: [ main, feature/asciidoc ]
jobs:
  build-job:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:1.38
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Create output directory
        run: mkdir -p out
      - name: Build documents
        run: ./build-documents.sh asciidoctor-pdf
      - name: Upload documents
        uses: actions/upload-artifact@v3
        with:
          name: documents
          path: out