name: Build Documents
on:
  push:
    branches: [ main, feature/pandoc ]
jobs:
  build-job:
    runs-on: ubuntu-latest
    container:
      image: rstropek/pandoc-latex
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Create output directory
        run: mkdir -p out
      - name: Build documents
        run: ./build-documents.sh pandoc
      - name: Upload documents
        uses: actions/upload-artifact@v2
        with:
          name: documents
          path: out