name: Build Documents
on:
  push:
    branches: [ main, feature/asciidoc ]
jobs:
  build-job:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:1.38
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Create output directory
        run: mkdir -p out
      - name: Build documents
        run: ./build-documents.sh asciidoctor-pdf asciidoctor
      - name: Upload exercise document as PDF
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: exercises-pdf
          path: out/pdf/index.pdf
      - name: Upload exercise document as HTML
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: exercises-html
          path: out/html/index.html
      - name: Setup pages
        if: success()
        uses: actions/configure-pages@v3
      - name: Upload HTML
        if: success()
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'out/html'
      - name: Deploy to GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@v1