name: Build Documents
on:
  push:
    branches: [ main, feature/asciidoc ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:1.38
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Create output directory
        run: mkdir -p out
      - name: Build documents
        run: ./build-documents.sh asciidoctor-pdf asciidoctor
      - name: Upload exercise document as PDF
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: exercises-pdf
          path: out/pdf/index.pdf
      - name: Upload exercise document as HTML
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: exercises-html
          path: out/html/index.html
      - name: Upload to GitHub Pages
        if: success()
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'out/html'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1